Pages/Account/ForgotPassword.cshtml.cs
using AdminTool.Extensions;
using AdminTool.Extensions.GoogleCaptcha;
using Jexpa.Core.EntityClasses;
using Jexpa.Core.Enums;
using Jexpa.Core.MemoryClasses;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace AdminTool.Pages.Account
{
    public class ForgotPasswordModel : SharedPageModel
    {
        private readonly GoogleCaptchaService _service;
        [Required]
        [BindProperty]
        public string Email { get; set; }
        [BindProperty]
        public string CaptchaToken { get; set; }
        public string Token { get; set; } = string.Empty;
        [BindProperty]
        public string ErrorMessage { get; set; } = string.Empty;

        public ForgotPasswordModel(GoogleCaptchaService service)
        {
            _service = service;
        }
        public void OnGet()
        {
            if (IsAuthenticated)
            {
                Response.Redirect("/");
            }
        }

        private async Task<bool> GenerateResetToken()
        {

            string errorInfo = string.Empty;
            if (string.IsNullOrEmpty(Email))
            {
                errorInfo = "<p>Please enter your email address.</p>";
            }
            else if (!(new EmailAddressAttribute().IsValid(Email)))
            {
                errorInfo = "<p>Please enter a valid email address.</p>";
            }
            else
            {
                Token = CUser.GenerateResetPasswordToken(BrandUrl, Email);
                if (string.IsNullOrEmpty(Token))
                {
                    errorInfo += "<p>There was an error generating your reset token. Please try again later.</p>";
                }
            }

            if (!string.IsNullOrEmpty(errorInfo))
            {
                ErrorMessage = errorInfo;
                return false;
            }
            return true;
        }

        public async Task<IActionResult> OnPostSendForgotPasswordEmail()
        {
            var captchaResult = await _service.VerifyToken(CaptchaToken);

            if (!captchaResult)
            {
                return Page();
            }

            if (await GenerateResetToken())
            {
                string nickname = CUser.GetByEmail(BrandUrl, Email).GetNickName();

                var templateDictionary = new Dictionary<string, object>
                {
                    { "BrandUrl", HttpContext.Request.Host },
                    { "NickName", nickname },
                    { "ResetPasswordLink", GetResetPasswordUrl() }
                };
                var cBrand = CBrand.GetByUrl(BrandUrl);
                var cPattern = CPattern.GetByCode("FORGOT_PASSWORD");
                CMail cMail = new CMail();
                cMail.AddFrom(cBrand.GetEmailSupportTitle(), cBrand.GetEmailSupport());
                cMail.AddTo(nickname ?? "", Email);
                cMail.SetSubject(cPattern.GetSubject(CountryCode.US));
                cMail.SetBody(cPattern.GetContent(CountryCode.US), templateDictionary);
                cMail.Send();
            }
            return Page();
        }

        private string GetResetPasswordUrl()
        {
            return $"{HttpContext.Request.Host}/account/reset-password?email={Email}&token={Uri.EscapeDataString(Token)}";
        }
    }
}

Pages/Account/Login.cshtml.cs
using AdminTool.Extensions;
using AdminTool.Extensions.GoogleCaptcha;
using AdminTool.Pages;
using Jexpa.Core.EntityClasses;
using Jexpa.Core.Enums;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace AdminTool.Pages.Account
{
    public class LoginModel : SharedPageModel
    {
        private readonly GoogleCaptchaService _service;

        public LoginModel(GoogleCaptchaService service)
        {
            _service = service;
        }
        [BindProperty]
        public int Counter { get; set; } = 0;
        [BindProperty]
        public string Username { get; set; } = string.Empty;
        [BindProperty]
        public string Password { get; set; }
        [BindProperty]
        public string CaptchaToken { get; set; }
        public string ErrorMessage { get; set; } = string.Empty;

        public void OnGet()
        {
            if (IsAuthenticated)
            {
                Response.Redirect("/");
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            LoginStatus loginStatus;
          
            if (IsAuthenticated)
            {
                return RedirectToPage("/Index");
            }

            if (HttpContext.Session.GetFailedCounter() > 3)
            {
                var captchaResult = await _service.VerifyToken(CaptchaToken);

                if (!captchaResult)
                {
                    return Page();
                }
            }

            if (string.IsNullOrEmpty(Username) || string.IsNullOrEmpty(Password))
            {
                ErrorMessage = "Username and password are required.";
                return Page();
            }

            loginStatus = CUser.LoginWithUsername(BrandUrl, Username, Password);

            if (loginStatus == LoginStatus.Success)
            {
                HttpContext.Session.SetCurrentUser(CUser.GetByUsername(BrandUrl, Username));
                return RedirectToPage("/Index");
            }
            HttpContext.Session.FailedCounter();
            ErrorMessage = "Invalid username or password.";
            return Page();
        }
    }
}

Pages/Account/Register.cshtml.cs
using AdminTool.Extensions.GoogleCaptcha;
using Jexpa.Core.EntityClasses;
using Jexpa.Core.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace AdminTool.Pages.Account
{
    public class RegisterModel : SharedPageModel
    {
        private readonly GoogleCaptchaService _service;

        public class InputModel
        {
            [Required(ErrorMessage = "The username must not null")]
            public string Username { get; set; }
            [Required(ErrorMessage = "The email must not null")]
            [DataType(DataType.EmailAddress)]
            public string Email { get; set; }
            [Required(ErrorMessage = "The password must not null")]
            [DataType(DataType.Password)]
            public string Password { get; set; }
            [Required(ErrorMessage = "The confirm password must not null")]
            [DataType(DataType.Password)]
            [Compare("Password", ErrorMessage = "Password and Confirm Password must match")]
            public string ConfirmPassword { get; set; }
            public string CaptchaToken { get; set; }
        }
        [BindProperty]
        public InputModel inputModel { get; set; }
        public CUser NewUser { get; set; }

        public RegisterModel(GoogleCaptchaService service)
        {
            _service = service;
        }
        public void OnGet()
        {
            if (IsAuthenticated)
            {
                Response.Redirect("/");
            }
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {

            var captchaResult = await _service.VerifyToken(inputModel.CaptchaToken);

            if (!captchaResult)
            {
                return Page();
            }
            if (ModelState.IsValid)
            {
                RegistrationStatus status = CUser.RegisterUser(BrandUrl, inputModel.Username, inputModel.Password, inputModel.Email);

                if (status == RegistrationStatus.Success)
                {
                    return RedirectToPage(returnUrl);
                }
            }
            return Page();
        }
    }
}

Pages/Account/ResetPassword.cshtml.cs
using AdminTool.Extensions.GoogleCaptcha;
using Jexpa.Core.EntityClasses;
using Jexpa.Core.Enums;
using Jexpa.Core.MemoryClasses;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Primitives;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AdminTool.Pages.Account
{
    public class ResetPasswordModel : SharedPageModel
    {
        private readonly GoogleCaptchaService _service;
        [BindProperty]
        public string Token { get; set; } = string.Empty;
        [BindProperty]
        [Required(ErrorMessage = "Email is required")]
        public string Email { get; set; } = string.Empty;
        [BindProperty]
        [Required(ErrorMessage = "New Password is required")]
        [Display(Name = "New Password")]
        public string NewPassword { get; set; } = string.Empty;
        [BindProperty]
        [Required(ErrorMessage = "Confirm Password is required")]
        [Display(Name = "Confirm Password")]
        [Compare(nameof(NewPassword), ErrorMessage = "Passwords don't match")]
        public string ConfirmPassword { get; set; } = string.Empty;
        [BindProperty]
        public string CaptchaToken { get; set; }
        public TokenStatus TokenStatus;
        public string ErrorMessage = string.Empty;

        public ResetPasswordModel(GoogleCaptchaService service)
        {
            _service = service;
        }
        public void OnGet()
        {
            StringValues values;
            string url = HttpContext.Request.QueryString.ToString();
            if (QueryHelpers.ParseQuery(url).TryGetValue("email", out values))
            {
                Email = values.FirstOrDefault();
            }
            if (QueryHelpers.ParseQuery(url).TryGetValue("token", out values))
            {
                Token = values.FirstOrDefault();
            }
            if(!string.IsNullOrEmpty(Email)&& !string.IsNullOrEmpty(Token))
            {
                TokenStatus = CToken.ValidateResetPasswordToken(CUser.GetByEmail(BrandUrl, Email), Token);
            }           
        }

        public async Task<IActionResult> OnPostChangePassword()
        {
            var captchaResult = await _service.VerifyToken(CaptchaToken);

            if (!captchaResult)
            {
                return Page();
            }

            var result = CUser.ResetPassword(BrandUrl, Email, Token, NewPassword);

            if (result != ResetPasswordStatus.Success)
            {
                ErrorMessage = $"<p>Got an error in calling ResetPassword: {result}</p>";
            }
            return RedirectToPage("/Account/Login");
        }
    }
}

Pages/Account/ForgotPassword.cshtml
@page
@model AdminTool.Pages.Account.ForgotPasswordModel

<section>
    <div class="flex justify-center items-center h-screen">
        <div class="max-w-md border-2 rounded-md bg-white w-full p-6 space-y-4">
            <div class="text-center flex flex-col justify-center items-center mb-4">
                <h1 class="font-bold tracking-wider text-xl mb-2 w-full text-gray-600">
                    Forgot Password
                </h1>
                @if (string.IsNullOrEmpty(Model.Token))
                {
                    <div class="py-2 text-left text-red-500 font-semibold">
                        @Html.Raw(Model.ErrorMessage)
                    </div>
                    <form method="post">
                        <input type="hidden" asp-for="CaptchaToken" />
                        <div class="" mb-4">
                            <label asp-for="Email" class="block mb-2 text-base text-gray-600 font-semibold"></label>
                            <input asp-for="Email" name="email" placeholder="Email" type="email"
                               class="py-2 px-3 border border-gray-300 focus:border-green-300 focus:outline-none focus:ring focus:ring-green-200 focus:ring-opacity-50 rounded-md shadow-sm disabled:bg-gray-100 mt-1 block w-full" />
                        </div>
                        <div class="mt-8">
                            <button asp-page-handler="SendForgotPasswordEmail" class="w-full px-4 py-2 tracking-wide text-white bg-green-500 transition-colors duration-200 transform rounded-md bg-primary hover:bg-green-400 focus:outline-none focus:bg-teal-400">
                                Continue
                            </button>
                        </div>
                    </form>

                }
                else
                {
                    <p class="p-2 font-semibold">The reset password link has been sent to your mail.</p>
                }
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @{
    <partial name="_CaptchaPartial" />
    <partial name="_ValidationScriptsPartial" />
    }
}

Pages/Account/Login.cshtml
@page
@model AdminTool.Pages.Account.LoginModel
@{
    ViewData["Title"] = "Login page";
}

<section>
    <div class="flex justify-center items-center h-screen">
        <div class="max-w-md border-2 rounded-md bg-white w-full p-6 space-y-4">
            <div class="flex flex-col justify-center items-center mb-4">
                <img src="~/images/logo.png" alt="Admin Tool" />
                <p class="text-xl text-center text-gray-600 ">Welcome back</p>
            </div>
            @if (Model.ErrorMessage != null)
            {
                <p class="text-red-600 text-center">
                    @Model.ErrorMessage
                </p>
            }
            <form method="post">
                @if (Model.Counter > 3)
                {
                    <input type="hidden" asp-for="CaptchaToken" />
                }
                <div class="mb-4">
                    <label for="username" class="block mb-2 text-base text-gray-600 font-semibold">Username</label>
                    <input asp-for="Username" type="text"
                           class="py-2 px-3 border border-gray-300 focus:border-green-300 focus:outline-none focus:ring focus:ring-green-200 focus:ring-opacity-50 rounded-md shadow-sm disabled:bg-gray-100 mt-1 block w-full"
                           placeholder="Enter your username">
                </div>
                <div class="mb-4">
                    <label for="password" class="block mb-2 text-base text-gray-600 font-semibold">Password</label>
                    <input asp-for="Password" type="password" name="password" placeholder="Enter your password"
                           class="py-2 px-3 border border-gray-300 focus:border-green-300 focus:outline-none focus:ring focus:ring-green-200 focus:ring-opacity-50 rounded-md shadow-sm disabled:bg-gray-100 mt-1 block w-full" />
                </div>
                <div class="flex justify-between mt-4">
                    <div class="flex items-center">
                        <input type="checkbox"
                               class="cursor-pointer border border-gray-300 focus:border-green-300 focus:outline-none focus:ring focus:ring-green-200 focus:ring-opacity-50 rounded-md shadow-sm disabled:bg-gray-100 mr-2">
                        <p>Remember Me</p>
                    </div>
                    <div class="">
                        <a asp-page="/Account/ForgotPassword" class="hover:underline hover:text-red-600">Forgot Your Password?</a>
                    </div>
                </div>
                <div class="mt-8">
                    <button type="submit"
                            class="w-full px-4 py-2 tracking-wide text-white bg-green-500 transition-colors duration-200 transform rounded-md bg-primary hover:bg-green-400 focus:outline-none focus:bg-teal-400">
                        Sign in
                    </button>
                </div>
            </form>
            <p class="text-center text-gray-300 text-sm">OR</p>
            <div class="flex items-center justify-between mt-4">
                <span class="w-1/5 border-b dark:border-gray-600 md:w-1/4"></span>
                <a asp-page="/Account/Register" class="text-xs text-gray-600 hover:text-gray-400 uppercase hover:underline">Create an account</a>
                <span class="w-1/5 border-b dark:border-gray-600 md:w-1/4"></span>
            </div>
        </div>
    </div>
</section>

@if (Model.Counter > 3) { }
@section Scripts {
    @{
    <partial name="_CaptchaPartial" />
    }
}

Pages/Account/Register.cshtml
@page
@using Jexpa.Core.Enums
@model AdminTool.Pages.Account.RegisterModel
@{
    ViewData["Title"] = "Register page";
}

<section>
    <div class="flex justify-center items-center h-screen">
        <div class="max-w-md border-2 w-full p-6 space-y-4 bg-white">
            <div class="mb-4">
                <h2 class="mb-3 text-center text-5xl text-green-700 font-extrabold">
                    Register
                </h2>
            </div>
            <form method="post" action="">
                <input type="hidden" id="CaptchaToken" asp-for="inputModel.CaptchaToken" />
                <div class="mb-4">
                    <label asp-for="inputModel.Username"
                           class="block mb-2 text-base text-gray-600 font-semibold"></label>
                    <input asp-for="inputModel.Username" type="text"
                           class="py-2 px-3 border border-gray-300 focus:border-green-300 focus:outline-none focus:ring focus:ring-green-200 focus:ring-opacity-50 rounded-md shadow-sm disabled:bg-gray-100 mt-1 block w-full" />
                    <span asp-validation-for="inputModel.Username" class="text-red-600"></span>
                </div>
                <div class="mb-4">
                    <label asp-for="inputModel.Email"
                           class="block mb-2 text-base text-gray-600 font-semibold"></label>
                    <input asp-for="inputModel.Email" type="email"
                           class="py-2 px-3 border border-gray-300 focus:border-green-300 focus:outline-none focus:ring focus:ring-green-200 focus:ring-opacity-50 rounded-md shadow-sm disabled:bg-gray-100 mt-1 block w-full" />
                    <span asp-validation-for="inputModel.Email" class="text-red-600"></span>
                </div>
                <div class="mb-4">
                    <label asp-for="inputModel.Password"
                           class="block mb-2 text-base text-gray-600 font-semibold"></label>
                    <input asp-for="inputModel.Password" type="password"
                           class="py-2 px-3 border border-gray-300 focus:border-green-300 focus:outline-none focus:ring focus:ring-green-200 focus:ring-opacity-50 rounded-md shadow-sm disabled:bg-gray-100 mt-1 block w-full" />
                    <span asp-validation-for="inputModel.Password" class="text-red-600"></span>
                </div>
                <div class="mb-4">
                    <label asp-for="inputModel.ConfirmPassword"
                           class="block mb-2 text-base text-gray-600 font-semibold"></label>
                    <input asp-for="inputModel.ConfirmPassword" type="password"
                           class="py-2 px-3 border border-gray-300 focus:border-green-300 focus:outline-none focus:ring focus:ring-green-200 focus:ring-opacity-50 rounded-md shadow-sm disabled:bg-gray-100 mt-1 block w-full" />
                    <span asp-validation-for="inputModel.ConfirmPassword" class="text-red-600"></span>
                </div>
                <div class="mt-8 flex justify-center">
                    <button type="submit"
                            class="w-1/3 px-4 py-2 tracking-wide text-white bg-green-500 transition-colors duration-200 transform rounded-md bg-primary hover:bg-green-400 focus:outline-none focus:bg-teal-400">
                        Create
                    </button>
                </div>
            </form>
        </div>
    </div>
</section>

@section Scripts {
    @{
    <partial name="_CaptchaPartial" />
    <partial name="_ValidationScriptsPartial" />
    }
}

Pages/Account/ResetPassword.cshtml
@page
@model AdminTool.Pages.Account.ResetPasswordModel

<section>
    @if (string.IsNullOrEmpty(Model.Token) || string.IsNullOrEmpty(Model.Email))
    {
        <h1 class="font-bold tracking-wider text-xl mb-2 w-full text-gray-600">
            Provided invalid url queries
        </h1>
    }
    else
    {
        <div class="flex justify-center items-center h-screen">
            <div class="max-w-md border-2 rounded-md bg-white w-full p-6 space-y-4">
                <div class="text-center flex flex-col justify-center items-center mb-4">
                    <h1 class="font-bold tracking-wider text-xl mb-2 w-full text-gray-600">
                        Reset your password
                    </h1>
                    <div class="py-2 text-left text-red-500 font-semibold">
                        @Html.Raw(Model.ErrorMessage)
                    </div>
                    <form method="post">
                        <input type="hidden" asp-for="CaptchaToken" />       
                        <input type="hidden" asp-for="Email" />  
                        <input type="hidden" asp-for="Token" />  
                        <div class="" mb-4">
                            <label asp-for="NewPassword" class="block mb-2 text-base text-gray-600 font-semibold"></label>
                            <input asp-for="NewPassword" type="password"
                               class="py-2 px-3 border border-gray-300 focus:border-green-300 focus:outline-none focus:ring focus:ring-green-200 focus:ring-opacity-50 rounded-md shadow-sm disabled:bg-gray-100 mt-1 block w-full" />
                            <span asp-validation-for="NewPassword" class="py-2 text-left text-red-500 font-semibold"></span>
                        </div>
                        <div class="" mb-4">
                            <label asp-for="ConfirmPassword" class="block mb-2 text-base text-gray-600 font-semibold"></label>
                            <input asp-for="ConfirmPassword" type="password"
                               class="py-2 px-3 border border-gray-300 focus:border-green-300 focus:outline-none focus:ring focus:ring-green-200 focus:ring-opacity-50 rounded-md shadow-sm disabled:bg-gray-100 mt-1 block w-full" />
                            <span asp-validation-for="ConfirmPassword" class="py-2 text-left text-red-500 font-semibold"></span>
                        </div>
                        <div class="mt-8">
                            <button asp-page-handler="ChangePassword" class="w-full px-4 py-2 tracking-wide text-white bg-green-500 transition-colors duration-200 transform rounded-md bg-primary hover:bg-green-400 focus:outline-none focus:bg-teal-400">
                                Continue
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    }

</section>

@section Scripts {
    @{
    <partial name="_CaptchaPartial" />
    <partial name="_ValidationScriptsPartial" />
    }
}